/** PUBG Steam inventory — weights + grouped catalog */
window.PUBG_ITEMS = {
  Health: {
    Bandage: 2,
    "First Aid Kit": 10,
    "Med Kit": 20,
    "Energy Drink": 4,
    Painkiller: 10,
    Adrenaline: 20,
  },
  Equipment: {
    "Helmet Level 1": 40,
    "Helmet Level 2": 50,
    "Helmet Level 3": 60,
    "Vest Level 1": 60,
    "Vest Level 2": 75,
    "Vest Level 3": 90,
    "Jammer Pack 1": 80,
    "Jammer Pack 2": 90,
    "Jammer Pack 3": 100,
  },
  Weapons: {
    AKM: 40,
    M416: 40,
    "SCAR-L": 40,
    "Beryl M762": 40,
    AUG: 40,
    Groza: 40,
    G36C: 40,
    M16A4: 40,
    ACE32: 40,
    Mk47: 40,
    QBZ: 40,
    FAMAS: 40,
    K2: 40,
    Kar98k: 50,
    M24: 50,
    AWM: 50,
    Mosin: 50,
    Win94: 45,
    "Lynx AMR": 55,
    SKS: 45,
    Mini14: 45,
    SLR: 45,
    VSS: 45,
    Dragunov: 45,
    Mk12: 45,
    Mk14: 50,
    UZI: 30,
    Vector: 30,
    UMP45: 30,
    Bizon: 30,
    MP5K: 30,
    P90: 30,
    "Tommy Gun": 30,
    MP9: 30,
    JS9: 30,
    S1897: 35,
    S12K: 35,
    DBS: 35,
    O12: 40,
    S686: 35,
    "Sawed-off": 25,
    "DP-28": 55,
    M249: 55,
    MG3: 55,
    RPD: 55,
    P92: 15,
    P1911: 15,
    Deagle: 15,
    Skorpion: 15,
    P18C: 15,
    R1895: 15,
    "Flare Gun": 20,
    Crossbow: 40,
    M79: 45,
    Mortar: 80,
    Panzerfaust: 70,
    "Stun Gun": 15,
    Pan: 20,
    Machete: 20,
    Crowbar: 20,
    Sickle: 20,
    Pickaxe: 20,
  },
  Attachments: {
    "Red Dot": 10,
    Holo: 10,
    "Canted Sight": 10,
    "Laser Sight": 10,
    "2x Scope": 15,
    "3x Scope": 15,
    "4x Scope": 15,
    "6x Scope": 15,
    "8x Scope": 20,
    "15x Scope": 20,
    "Vertical Grip": 10,
    "Angled Grip": 10,
    "Thumb Grip": 10,
    "Half Grip": 10,
    "Light Grip": 10,
    Compensator: 10,
    "Flash Hider": 10,
    Suppressor: 20,
    Choke: 5,
    "Extended Mag": 15,
    "Quickdraw Mag": 14,
    "Ext. Quickdraw Mag": 20,
    "Tactical Stock": 12,
    "Cheek Pad": 17,
    "Bullet Loops": 15,
    Quiver: 14,
  },
  Utility: {
    "Frag Grenade": 27,
    "Smoke Grenade": 14,
    "Stun Grenade": 12,
    Molotov: 16,
    "BZ Grenade": 23,
    C4: 35,
    "Cover Flare": 27,
    "Sticky Bomb": 25,
  },
  Ammo: {
    "9mm": 0.3,
    ".45 ACP": 0.4,
    "5.56mm": 0.5,
    "5.7mm": 0.4,
    "7.62mm": 0.6,
    "12 Gauge": 1.25,
    ".300 Magnum": 1,
    "40mm": 2,
    Rocket: 5,
    "Mortar Shell": 4,
  },
  Other: {
    "E Pickup": 50,
    "Gas Can": 20,
    Bicycle: 70,
    "Folded Shield": 30,
    Cable: 3,
    "Basement Key": 1,
    "Security Keycard": 1,
    "Blue Chip": 5,
  },
};

/** Extra info shown on cards (equip bonuses / notes) */
window.ITEM_META = {
  "Helmet Level 1": { noteKey: "armorOnly" },
  "Helmet Level 2": { noteKey: "armorOnly" },
  "Helmet Level 3": { noteKey: "armorOnly" },
  "Vest Level 1": { noteKey: "vestBonus", bonus: 50 },
  "Vest Level 2": { noteKey: "vestBonus", bonus: 50 },
  "Vest Level 3": { noteKey: "vestBonus", bonus: 50 },
  "Jammer Pack 1": { noteKey: "jammerBonus", bonus: 150 },
  "Jammer Pack 2": { noteKey: "jammerBonus", bonus: 200 },
  "Jammer Pack 3": { noteKey: "jammerBonus", bonus: 250 },
};

window.ITEM_GROUPS = {
  Equipment: [
    { id: "helmet", items: ["Helmet Level 1", "Helmet Level 2", "Helmet Level 3"] },
    { id: "vestGear", items: ["Vest Level 1", "Vest Level 2", "Vest Level 3"] },
    { id: "jammer", items: ["Jammer Pack 1", "Jammer Pack 2", "Jammer Pack 3"] },
  ],
  Weapons: [
    {
      id: "ar",
      items: [
        "AKM",
        "M416",
        "SCAR-L",
        "Beryl M762",
        "AUG",
        "Groza",
        "G36C",
        "M16A4",
        "ACE32",
        "Mk47",
        "QBZ",
        "FAMAS",
        "K2",
      ],
    },
    { id: "dmr", items: ["SKS", "Mini14", "SLR", "VSS", "Dragunov", "Mk12", "Mk14"] },
    { id: "sr", items: ["Kar98k", "M24", "AWM", "Mosin", "Win94", "Lynx AMR"] },
    { id: "smg", items: ["UZI", "Vector", "UMP45", "Bizon", "MP5K", "P90", "Tommy Gun", "MP9", "JS9"] },
    { id: "sg", items: ["S1897", "S12K", "DBS", "O12", "S686", "Sawed-off"] },
    { id: "lmg", items: ["DP-28", "M249", "MG3", "RPD"] },
    { id: "pistol", items: ["P92", "P1911", "Deagle", "Skorpion", "P18C", "R1895", "Flare Gun"] },
    { id: "special", items: ["Crossbow", "M79", "Mortar", "Panzerfaust", "Stun Gun"] },
    { id: "melee", items: ["Pan", "Machete", "Crowbar", "Sickle", "Pickaxe"] },
  ],
  Attachments: [
    {
      id: "optics",
      items: [
        "Red Dot",
        "Holo",
        "Canted Sight",
        "Laser Sight",
        "2x Scope",
        "3x Scope",
        "4x Scope",
        "6x Scope",
        "8x Scope",
        "15x Scope",
      ],
    },
    {
      id: "grip",
      items: ["Vertical Grip", "Angled Grip", "Thumb Grip", "Half Grip", "Light Grip"],
    },
    { id: "muzzle", items: ["Compensator", "Flash Hider", "Suppressor", "Choke"] },
    { id: "mag", items: ["Extended Mag", "Quickdraw Mag", "Ext. Quickdraw Mag"] },
    { id: "stock", items: ["Tactical Stock", "Cheek Pad", "Bullet Loops", "Quiver"] },
  ],
};

window.ITEM_IMAGES = {
  Bandage: "health/bandage.png",
  "First Aid Kit": "health/first-aid-kit.png",
  "Med Kit": "health/med-kit.png",
  "Energy Drink": "health/energy-drink.png",
  Painkiller: "health/painkiller.png",
  Adrenaline: "health/adrenaline.png",
  "Frag Grenade": "throwables/frag-grenade.png",
  "Smoke Grenade": "throwables/smoke-grenade.png",
  "Stun Grenade": "throwables/stun-grenade.png",
  Molotov: "throwables/molotov.png",
  "BZ Grenade": "throwables/bz-grenade.png",
  C4: "throwables/c4.png",
  "Cover Flare": "throwables/cover-flare.png",
  "Sticky Bomb": "throwables/sticky-bomb.webp",
  "9mm": "ammo/9mm.png",
  ".45 ACP": "ammo/45-acp.png",
  "5.56mm": "ammo/556mm.png",
  "5.7mm": "ammo/57mm.png",
  "7.62mm": "ammo/762mm.png",
  "12 Gauge": "ammo/12-gauge.png",
  ".300 Magnum": "ammo/300-magnum.png",
  "40mm": "ammo/12-gauge.png",
  Rocket: "ammo/300-magnum.png",
  "Mortar Shell": "ammo/12-gauge.png",
  "E Pickup": "other/e-pickup.png",
  "Gas Can": "other/gas-can.png",
  Bicycle: "other/bicycle.png",
  "Folded Shield": "other/folded-shield.png",
  Cable: "other/cable.png",
  "Basement Key": "other/basement-key.png",
  "Security Keycard": "other/security-keycard.png",
  "Blue Chip": "other/blue-chip.png",
  "Helmet Level 1": "equipment/helmet-1.png",
  "Helmet Level 2": "equipment/helmet-2.png",
  "Helmet Level 3": "equipment/helmet-3.png",
  "Vest Level 1": "equipment/vest-1.png",
  "Vest Level 2": "equipment/vest-2.png",
  "Vest Level 3": "equipment/vest-3.png",
  "Jammer Pack 1": "equipment/jammer-1.png",
  "Jammer Pack 2": "equipment/jammer-2.png",
  "Jammer Pack 3": "equipment/jammer-3.png",
  AKM: "weapons/akm.png",
  M416: "weapons/m416.png",
  "SCAR-L": "weapons/scar-l.png",
  "Beryl M762": "weapons/beryl-m762.png",
  AUG: "weapons/aug.png",
  Groza: "weapons/groza.png",
  G36C: "weapons/g36c.png",
  M16A4: "weapons/m16a4.png",
  ACE32: "weapons/ace32.png",
  Mk47: "weapons/mk47.png",
  QBZ: "weapons/qbz.png",
  FAMAS: "weapons/famas.png",
  K2: "weapons/k2.webp",
  Kar98k: "weapons/kar98k.png",
  M24: "weapons/m24.png",
  AWM: "weapons/awm.png",
  Mosin: "weapons/mosin.png",
  Win94: "weapons/win94.png",
  "Lynx AMR": "weapons/lynx-amr.png",
  SKS: "weapons/sks.png",
  Mini14: "weapons/mini14.png",
  SLR: "weapons/slr.png",
  VSS: "weapons/vss.png",
  Dragunov: "weapons/dragunov.png",
  Mk12: "weapons/mk12.webp",
  Mk14: "weapons/mk14.webp",
  UZI: "weapons/uzi.png",
  Vector: "weapons/vector.png",
  UMP45: "weapons/ump45.png",
  Bizon: "weapons/bizon.png",
  MP5K: "weapons/mp5k.png",
  P90: "weapons/p90.png",
  "Tommy Gun": "weapons/tommy-gun.webp",
  MP9: "weapons/mp9.webp",
  JS9: "weapons/js9.webp",
  S1897: "weapons/s1897.png",
  S12K: "weapons/s12k.png",
  DBS: "weapons/dbs.png",
  O12: "weapons/o12.png",
  S686: "weapons/s686.webp",
  "Sawed-off": "weapons/sawed-off.webp",
  "DP-28": "weapons/dp-28.png",
  M249: "weapons/m249.png",
  MG3: "weapons/mg3.png",
  RPD: "weapons/rpd.webp",
  P92: "weapons/p92.png",
  P1911: "weapons/p1911.png",
  Deagle: "weapons/deagle.png",
  Skorpion: "weapons/skorpion.png",
  P18C: "weapons/p18c.webp",
  R1895: "weapons/r1895.webp",
  "Flare Gun": "weapons/flare-gun.png",
  Crossbow: "weapons/crossbow.png",
  M79: "weapons/m79.webp",
  Mortar: "weapons/mortar.webp",
  Panzerfaust: "weapons/panzerfaust.webp",
  "Stun Gun": "weapons/stun-gun.webp",
  Pan: "weapons/pan.png",
  Machete: "weapons/machete.png",
  Crowbar: "weapons/crowbar.png",
  Sickle: "weapons/sickle.webp",
  Pickaxe: "weapons/pickaxe.webp",
  "Red Dot": "attachments/red-dot.png",
  Holo: "attachments/holo.png",
  "Canted Sight": "attachments/canted-sight.png",
  "Laser Sight": "attachments/laser-sight.png",
  "2x Scope": "attachments/2x-scope.png",
  "3x Scope": "attachments/3x-scope.png",
  "4x Scope": "attachments/4x-scope.png",
  "6x Scope": "attachments/6x-scope.png",
  "8x Scope": "attachments/8x-scope.png",
  "15x Scope": "attachments/15x-scope.png",
  "Vertical Grip": "attachments/vertical-grip.png",
  "Angled Grip": "attachments/angled-grip.png",
  "Thumb Grip": "attachments/thumb-grip.png",
  "Half Grip": "attachments/half-grip.png",
  "Light Grip": "attachments/light-grip.png",
  Compensator: "attachments/compensator.png",
  "Flash Hider": "attachments/flash-hider.png",
  Suppressor: "attachments/suppressor.png",
  Choke: "attachments/choke.png",
  "Extended Mag": "attachments/extended-mag.png",
  "Quickdraw Mag": "attachments/quickdraw-mag.png",
  "Ext. Quickdraw Mag": "attachments/extended-mag.png",
  "Tactical Stock": "attachments/tactical-stock.png",
  "Cheek Pad": "attachments/cheek-pad.png",
  "Bullet Loops": "attachments/tactical-stock.png",
  Quiver: "attachments/quiver.png",
};

window.BACKPACK_CAPACITY = { 1: 150, 2: 200, 3: 250 };
window.BASE_CAPACITY = 70;
window.VEST_CAPACITY = 50;

/** Suggested ammo count by weapon class (PUBG mid-late game loadout). */
window.AMMO_RECOMMEND = {
  ar: 180,
  dmr: 90,
  sr: 40,
  smg: 200,
  sg: 30,
  lmg: 200,
  pistol: 60,
  special: 0,
  melee: 0,
};
