/** PUBG maps + Secret Basement 2026
 *  Clean guide images only (no double-painted circles).
 *  Pins sit on the ORIGINAL red marks from the guide photos.
 */
window.PUBG_MAPS = [
  { id: "erangel", size: "8x8", type: "classic", secret: true },
  { id: "miramar", size: "8x8", type: "classic", secret: true },
  { id: "sanhok", size: "4x4", type: "small", secret: false },
  { id: "vikendi", size: "8x8", type: "classic", secret: true },
  { id: "karakin", size: "2x2", type: "small", secret: false },
  { id: "paramo", size: "3x3", type: "small", secret: true },
  { id: "taego", size: "8x8", type: "classic", secret: true },
  { id: "deston", size: "8x8", type: "classic", secret: true },
  { id: "rondo", size: "8x8", type: "classic", secret: true },
];

/** Official-style clean maps for distance measuring (local assets). */
window.ORIGINAL_MAPS = window.PUBG_MAPS.map((m) => ({
  mapId: m.id,
  size: m.size,
  image: `images/maps/original/${m.id}.jpg`,
}));

window.SECRET_BASEMENTS_2026 = [
  {
    mapId: "erangel",
    image: "images/maps/secrets/erangel.jpg",
    rooms: 15,
    keyId: "Basement Key",
    entrance: "wood",
    year: 2026,
    builtInMarkers: true,
    pins: [
      { id: "e1", x: 62.38, y: 7.51, loc: "northCoast", area: "north", building: "coastHouse", tip: "redPlank" },
      { id: "e2", x: 15.58, y: 22.15, loc: "zharki", area: "northWest", building: "villageHouse", tip: "redPlank" },
      { id: "e3", x: 49.92, y: 23.42, loc: "severny", area: "north", building: "apartment", tip: "redPlank" },
      { id: "e4", x: 79.79, y: 24.86, loc: "kameshki", area: "northEast", building: "villageHouse", tip: "redPlank" },
      { id: "e5", x: 30.71, y: 27.07, loc: "georgopol", area: "northWest", building: "containers", tip: "redPlank" },
      { id: "e6", x: 67.92, y: 41.88, loc: "yasnaya", area: "northEast", building: "houseCluster", tip: "redPlank" },
      { id: "e7", x: 17.46, y: 43.07, loc: "gatka", area: "west", building: "villageHouse", tip: "redPlank" },
      { id: "e8", x: 37.5, y: 45.65, loc: "school", area: "northMid", building: "schoolYard", tip: "redPlank" },
      { id: "e9", x: 58.17, y: 54.14, loc: "pochinki", area: "center", building: "twoStory", tip: "redPlank" },
      { id: "e10", x: 84.17, y: 60.29, loc: "mylta", area: "east", building: "powerPlant", tip: "redPlank" },
      { id: "e11", x: 33.17, y: 62.75, loc: "quarry", area: "west", building: "villageHouse", tip: "redPlank" },
      { id: "e12", x: 14.54, y: 67.67, loc: "primorsk", area: "southWest", building: "coastHouse", tip: "redPlank" },
      { id: "e13", x: 53.38, y: 72.68, loc: "milBaseN", area: "south", building: "milBarracks", tip: "redPlank" },
      { id: "e14", x: 39.58, y: 82.44, loc: "milBaseW", area: "south", building: "milWarehouse", tip: "redPlank" },
      { id: "e15", x: 70.5, y: 82.57, loc: "sosnovkaSE", area: "southEast", building: "milDock", tip: "redPlank" },
    ],
  },
  {
    mapId: "miramar",
    image: "images/maps/secrets/miramar.jpg",
    // Live crop of cyan + red dashed-ring marks only (not vehicle/gas icons)
    pinCloseup: true,
    rooms: 15,
    keyId: "Basement Key",
    entrance: "mine",
    year: 2026,
    noteKey: "miramarNew",
    builtInMarkers: true,
    pins: [
      { id: "m1", x: 39.63, y: 13.21, loc: "oasis", area: "north", building: "rockMine", tip: "mineDoor" },
      { id: "m2", x: 56.11, y: 17.76, loc: "campoMilitar", area: "north", building: "hillMine", tip: "mineDoor" },
      { id: "m3", x: 21.45, y: 20.88, loc: "impala", area: "west", building: "rockMine", tip: "mineDoor" },
      { id: "m4", x: 76.56, y: 24.01, loc: "laCobreria", area: "east", building: "cliffMine", tip: "mineDoor" },
      { id: "m5", x: 33.66, y: 30.82, loc: "craterFields", area: "west", building: "mineShaft", tip: "mineDoor" },
      { id: "m6", x: 62.64, y: 39.35, loc: "minasGenerales", area: "east", building: "hillMine", tip: "mineDoor" },
      { id: "m7", x: 16.62, y: 40.48, loc: "hacienda", area: "west", building: "rockMine", tip: "mineDoor" },
      { id: "m8", x: 46.45, y: 48.15, loc: "pecado", area: "center", building: "rockMine", tip: "mineDoor", closeup: "images/maps/closeups/miramar-pin-pecado.jpg" },
      { id: "m9", x: 75.43, y: 52.13, loc: "losLeones", area: "southEast", building: "hillMine", tip: "mineDoor" },
      { id: "m10", x: 32.53, y: 61.22, loc: "monteNuevo", area: "southWest", building: "hillMine", tip: "mineDoor" },
      { id: "m11", x: 53.84, y: 63.78, loc: "alcantara", area: "south", building: "mineShaft", tip: "mineDoor" },
      { id: "m12", x: 15.77, y: 65.2, loc: "valleDelMar", area: "southWest", building: "rockMine", tip: "mineDoor" },
      { id: "m13", x: 63.72, y: 77.45, loc: "puertoParaiso", area: "south", building: "cliffMine", tip: "mineDoor" },
      { id: "m14", x: 39.35, y: 81.68, loc: "prison", area: "south", building: "mineShaft", tip: "mineDoor" },
      { id: "m15", x: 16.62, y: 89.06, loc: "partona", area: "southWest", building: "hillMine", tip: "mineDoor" },
    ],
  },
  {
    mapId: "rondo",
    image: "images/maps/secrets/rondo.jpg",
    rooms: 11,
    keyId: "Basement Key",
    entrance: "bunker",
    year: 2026,
    builtInMarkers: true,
    // Detected from secret-room icons (red broken ring + green center) — not garage squares
    pins: [
      { id: "r1", x: 61.76, y: 25.19, loc: "raiAn", area: "north", building: "urbanBunker", tip: "securityDoor" },
      { id: "r2", x: 46.43, y: 32.69, loc: "bamboo", area: "north", building: "compoundBasement", tip: "securityDoor" },
      { id: "r3", x: 17.4, y: 39.76, loc: "fongTun", area: "west", building: "compoundBasement", tip: "securityDoor" },
      { id: "r4", x: 81.33, y: 52.5, loc: "meyRan", area: "east", building: "warehouseHatch", tip: "securityDoor" },
      { id: "r5", x: 57.21, y: 53.98, loc: "neoxFactory", area: "center", building: "factoryFloor", tip: "securityDoor" },
      { id: "r6", x: 42.83, y: 54.98, loc: "jaeTin", area: "west", building: "urbanBunker", tip: "securityDoor" },
      { id: "r7", x: 9.4, y: 66.07, loc: "rinJiang", area: "southWest", building: "compoundBasement", tip: "securityDoor" },
      { id: "r8", x: 87.98, y: 66.36, loc: "hemayTown", area: "east", building: "compoundBasement", tip: "securityDoor" },
      { id: "r9", x: 84.57, y: 77.62, loc: "jadenaCity", area: "southEast", building: "urbanBunker", tip: "securityDoor" },
      { id: "r10", x: 15.4, y: 79.86, loc: "longHo", area: "southWest", building: "compoundBasement", tip: "securityDoor" },
      { id: "r11", x: 41.52, y: 85.9, loc: "tinLong", area: "south", building: "warehouseHatch", tip: "securityDoor" },
    ],
  },
  {
    mapId: "taego",
    image: "images/maps/secrets/taego.jpg",
    rooms: 18,
    keyId: "Basement Key",
    entrance: "blueRoof",
    year: 2026,
    builtInMarkers: true,
    pins: [
      { id: "t1", x: 52.73, y: 10.74, loc: "goDokN", area: "north", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t2", x: 31.74, y: 16.63, loc: "wolSongW", area: "northWest", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t3", x: 59.09, y: 20.88, loc: "yongCheon", area: "north", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t4", x: 21.67, y: 23.14, loc: "westIsland", area: "northWest", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t5", x: 43.65, y: 23.98, loc: "yongCheon", area: "north", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t6", x: 84.54, y: 25.53, loc: "eastCoast", area: "northEast", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t7", x: 93.57, y: 27.53, loc: "airportN", area: "northEast", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t8", x: 45.47, y: 32.17, loc: "yongCheon", area: "north", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t9", x: 77.92, y: 33.67, loc: "kangNeung", area: "east", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t10", x: 86.67, y: 41.3, loc: "eastCoast", area: "east", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t11", x: 61.52, y: 43.97, loc: "terminalE", area: "center", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t12", x: 73.59, y: 47.68, loc: "kangNeung", area: "east", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t13", x: 49.37, y: 57.27, loc: "terminalE", area: "center", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t14", x: 54.14, y: 60.83, loc: "terminalE", area: "center", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t15", x: 78.29, y: 68.13, loc: "ohHyang", area: "southEast", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t16", x: 78.92, y: 78.47, loc: "southTip", area: "southEast", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t17", x: 60.49, y: 78.58, loc: "ohHyang", area: "south", building: "blueRoofHouse", tip: "floorHatch" },
      { id: "t18", x: 29.64, y: 79.18, loc: "haPo", area: "southWest", building: "blueRoofHouse", tip: "floorHatch" },
    ],
  },
  {
    mapId: "deston",
    image: "images/maps/secrets/deston.jpg",
    rooms: 15,
    keyId: "Security Keycard",
    entrance: "security",
    year: 2026,
    builtInMarkers: true,
    pins: [
      { id: "d1", x: 32.59, y: 3.63, loc: "tenants", area: "north", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d2", x: 61.31, y: 7.26, loc: "carpenters", area: "north", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d3", x: 88.9, y: 32.22, loc: "windFarm", area: "east", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d4", x: 54.18, y: 32.78, loc: "buxley", area: "center", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d5", x: 20.33, y: 41.35, loc: "cavala", area: "west", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d6", x: 39.35, y: 42.66, loc: "turrita", area: "west", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d7", x: 57.24, y: 49.98, loc: "arena", area: "center", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d8", x: 80.45, y: 50.17, loc: "ripton", area: "east", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d9", x: 73.26, y: 51.61, loc: "ripton", area: "east", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d10", x: 48.3, y: 53.74, loc: "lod", area: "center", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d11", x: 19.27, y: 53.99, loc: "cavala", area: "west", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d12", x: 72.63, y: 58.05, loc: "riptonS", area: "southEast", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d13", x: 42.92, y: 68.38, loc: "sancarna", area: "southWest", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d14", x: 14.76, y: 72.26, loc: "elKoro", area: "southWest", building: "pillarRoom", tip: "keycardDoor" },
      { id: "d15", x: 68.5, y: 75.07, loc: "holston", area: "south", building: "pillarRoom", tip: "keycardDoor" },
    ],
  },
  {
    mapId: "paramo",
    image: "images/maps/secrets/paramo.jpg",
    rooms: 8,
    keyId: "Basement Key",
    entrance: "pyramid",
    year: 2026,
    builtInMarkers: true,
    // Detected from PURPLE arrow+circle secret-room marks on the guide
    pins: [
      { id: "p1", x: 39.7, y: 31.62, loc: "labN", area: "north", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p2", x: 27.66, y: 35.82, loc: "capacoN", area: "northWest", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p3", x: 62.43, y: 49.06, loc: "labSE", area: "east", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p4", x: 81.72, y: 57.33, loc: "atahul", area: "east", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p5", x: 60.39, y: 60.25, loc: "helipadE", area: "center", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p6", x: 43.36, y: 63.08, loc: "capacoS", area: "west", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p7", x: 12.79, y: 63.5, loc: "capacoW", area: "west", building: "pyramidDoor", tip: "simpleKey" },
      { id: "p8", x: 51.76, y: 80.34, loc: "makaiya", area: "south", building: "pyramidDoor", tip: "simpleKey" },
    ],
  },
  {
    mapId: "vikendi",
    image: "images/maps/secrets/vikendi.jpg",
    rooms: 10,
    keyId: "Security Keycard",
    entrance: "lab",
    year: 2026,
    builtInMarkers: true,
    // Detected from GREEN secret-key circles on the guide (not red/yellow icons)
    pins: [
      { id: "v1", x: 68.1, y: 12.46, loc: "cosmodrome", area: "north", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v2", x: 30.72, y: 15.48, loc: "coalMineN", area: "northWest", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v3", x: 82.02, y: 27.7, loc: "naros", area: "northEast", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v4", x: 49.96, y: 37.34, loc: "laveni", area: "center", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v5", x: 89.26, y: 46.76, loc: "dinoland", area: "east", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v6", x: 11.61, y: 46.88, loc: "winery", area: "west", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v7", x: 59.68, y: 61.18, loc: "castle", area: "south", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v8", x: 25.47, y: 69.81, loc: "krunik", area: "southWest", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v9", x: 79.75, y: 73.68, loc: "lumberYard", area: "southEast", building: "secretKeyHouse", tip: "keycardDoor" },
      { id: "v10", x: 46.85, y: 82.3, loc: "dekaMesto", area: "south", building: "secretKeyHouse", tip: "keycardDoor" },
    ],
  },
];

window.MAP_SERVICES_2026 = [
  {
    mapId: "erangel",
    image: "images/maps/services/erangel.jpg",
    pinCloseup: true,
    builtInMarkers: true,
    rooms: 63,
    pins: [
      { id: "ers1", x: 53.81, y: 12.44, loc: "svcSpot", area: "north", kind: "gas" },
      { id: "ers2", x: 68.21, y: 71.45, loc: "svcSpot", area: "southEast", kind: "gas" },
      { id: "ers3", x: 81.41, y: 61.3, loc: "svcSpot", area: "east", kind: "gas" },
      { id: "ers4", x: 58.28, y: 29.33, loc: "svcSpot", area: "north", kind: "gas" },
      { id: "ers5", x: 18.52, y: 32.22, loc: "svcSpot", area: "northWest", kind: "gas" },
      { id: "ers6", x: 40.32, y: 63.59, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "ers7", x: 10.92, y: 57.34, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "ers8", x: 81.42, y: 13.51, loc: "svcSpot", area: "northEast", kind: "gas" },
      { id: "ers9", x: 68.53, y: 4.64, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "ers10", x: 74.23, y: 74.77, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "ers11", x: 17.59, y: 34.62, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ers12", x: 63.25, y: 55.16, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers13", x: 12.69, y: 63.27, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ers14", x: 21.99, y: 17.6, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "ers15", x: 84.54, y: 39.4, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "ers16", x: 79.34, y: 50.4, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "ers17", x: 12.2, y: 53.31, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ers18", x: 56.6, y: 10.86, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "ers19", x: 46.6, y: 14.76, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "ers20", x: 21.34, y: 55.16, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ers21", x: 20.71, y: 41.16, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ers22", x: 54.89, y: 79.31, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "ers23", x: 46.2, y: 36.36, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers24", x: 18.54, y: 73.01, loc: "svcSpot", area: "southWest", kind: "vehicle" },
      { id: "ers25", x: 36.44, y: 65.35, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers26", x: 68.9, y: 15.2, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "ers27", x: 50.34, y: 41.37, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers28", x: 85.88, y: 56.3, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "ers29", x: 71.75, y: 56.91, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "ers30", x: 33.45, y: 51.26, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers31", x: 26.29, y: 46.96, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ers32", x: 82.7, y: 10.86, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "ers33", x: 81.84, y: 20.36, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "ers34", x: 64.35, y: 45.2, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers35", x: 60.8, y: 22.01, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "ers36", x: 39.13, y: 39.96, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers37", x: 13.48, y: 15.96, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "ers38", x: 31.8, y: 29.71, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "ers39", x: 53.34, y: 56.01, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers40", x: 55.14, y: 37.07, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers41", x: 66.39, y: 28.47, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "ers42", x: 67.96, y: 72.6, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "ers43", x: 45.61, y: 49.85, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ers44", x: 43.94, y: 28.47, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "ers45", x: 46.25, y: 72.0, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "ers46", x: 36.45, y: 15.55, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "ers47", x: 74.54, y: 31.01, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "ers48", x: 92.21, y: 77.32, loc: "svcSpot", area: "southEast", kind: "glider" },
      { id: "ers49", x: 53.18, y: 13.2, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "ers50", x: 20.39, y: 18.15, loc: "svcSpot", area: "northWest", kind: "glider" },
      { id: "ers51", x: 15.49, y: 69.08, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "ers52", x: 18.65, y: 43.08, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "ers53", x: 63.14, y: 8.04, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "ers54", x: 54.31, y: 72.11, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "ers55", x: 79.13, y: 25.52, loc: "svcSpot", area: "northEast", kind: "glider" },
      { id: "ers56", x: 40.12, y: 81.25, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "ers57", x: 17.54, y: 43.35, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "ers58", x: 37.01, y: 46.46, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "ers59", x: 53.96, y: 72.87, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "ers60", x: 62.39, y: 7.58, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "ers61", x: 82.39, y: 59.29, loc: "svcSpot", area: "east", kind: "glider" },
      { id: "ers62", x: 69.13, y: 81.66, loc: "svcSpot", area: "southEast", kind: "glider" },
      { id: "ers63", x: 56.93, y: 78.36, loc: "svcSpot", area: "south", kind: "boat" },
    ],
  },
  {
    mapId: "miramar",
    image: "images/maps/services/miramar.jpg",
    pinCloseup: true,
    builtInMarkers: true,
    rooms: 56,
    pins: [
      { id: "mis1", x: 73.12, y: 76.89, loc: "svcSpot", area: "southEast", kind: "gas" },
      { id: "mis2", x: 53.28, y: 26.4, loc: "svcSpot", area: "north", kind: "gas" },
      { id: "mis3", x: 72.93, y: 30.55, loc: "svcSpot", area: "northEast", kind: "gas" },
      { id: "mis4", x: 22.35, y: 47.87, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "mis5", x: 45.94, y: 5.77, loc: "svcSpot", area: "north", kind: "gas" },
      { id: "mis6", x: 34.53, y: 52.81, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "mis7", x: 31.33, y: 17.11, loc: "svcSpot", area: "northWest", kind: "gas" },
      { id: "mis8", x: 20.71, y: 33.67, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "mis9", x: 12.34, y: 27.26, loc: "svcSpot", area: "northWest", kind: "gas" },
      { id: "mis10", x: 47.35, y: 52.81, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "mis11", x: 23.67, y: 77.72, loc: "svcSpot", area: "southWest", kind: "gas" },
      { id: "mis12", x: 73.86, y: 44.26, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "mis13", x: 54.46, y: 27.74, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "mis14", x: 33.54, y: 63.41, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis15", x: 20.97, y: 57.59, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "mis16", x: 14.07, y: 23.01, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "mis17", x: 61.7, y: 43.31, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis18", x: 69.75, y: 34.46, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "mis19", x: 48.66, y: 13.77, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "mis20", x: 41.36, y: 66.59, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "mis21", x: 25.62, y: 49.41, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "mis22", x: 11.39, y: 60.79, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "mis23", x: 72.27, y: 9.45, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "mis24", x: 18.31, y: 72.55, loc: "svcSpot", area: "southWest", kind: "vehicle" },
      { id: "mis25", x: 37.97, y: 6.48, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "mis26", x: 29.63, y: 75.51, loc: "svcSpot", area: "southWest", kind: "vehicle" },
      { id: "mis27", x: 48.54, y: 35.94, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis28", x: 60.64, y: 69.25, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "mis29", x: 57.08, y: 65.54, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis30", x: 11.03, y: 26.3, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "mis31", x: 34.49, y: 26.36, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "mis32", x: 19.05, y: 36.29, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "mis33", x: 6.46, y: 39.1, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "mis34", x: 67.83, y: 16.26, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "mis35", x: 56.8, y: 8.97, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "mis36", x: 38.12, y: 43.43, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis37", x: 58.58, y: 51.01, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis38", x: 44.21, y: 51.24, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "mis39", x: 63.4, y: 77.66, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "mis40", x: 44.03, y: 15.91, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "mis41", x: 15.29, y: 24.81, loc: "svcSpot", area: "northWest", kind: "glider" },
      { id: "mis42", x: 20.71, y: 18.31, loc: "svcSpot", area: "northWest", kind: "glider" },
      { id: "mis43", x: 14.66, y: 51.05, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "mis44", x: 13.2, y: 66.91, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "mis45", x: 61.09, y: 7.22, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "mis46", x: 69.19, y: 74.95, loc: "svcSpot", area: "southEast", kind: "glider" },
      { id: "mis47", x: 40.59, y: 6.05, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "mis48", x: 27.22, y: 71.44, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "mis49", x: 4.8, y: 23.87, loc: "svcSpot", area: "northWest", kind: "glider" },
      { id: "mis50", x: 18.61, y: 39.55, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "mis51", x: 51.69, y: 5.66, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "mis52", x: 21.3, y: 55.7, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "mis53", x: 24.9, y: 12.54, loc: "svcSpot", area: "northWest", kind: "glider" },
      { id: "mis54", x: 7.05, y: 34.03, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "mis55", x: 11.78, y: 74.88, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "mis56", x: 10.53, y: 9.81, loc: "svcSpot", area: "northWest", kind: "glider" },
    ],
  },
  {
    mapId: "taego",
    image: "images/maps/services/taego.jpg",
    pinCloseup: true,
    builtInMarkers: true,
    rooms: 56,
    pins: [
      { id: "tas1", x: 30.67, y: 74.83, loc: "svcSpot", area: "southWest", kind: "gas" },
      { id: "tas2", x: 84.87, y: 34.09, loc: "svcSpot", area: "east", kind: "gas" },
      { id: "tas3", x: 58.87, y: 57.54, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "tas4", x: 27.86, y: 27.82, loc: "svcSpot", area: "northWest", kind: "gas" },
      { id: "tas5", x: 72.43, y: 41.09, loc: "svcSpot", area: "east", kind: "gas" },
      { id: "tas6", x: 43.37, y: 33.89, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "tas7", x: 55.53, y: 81.28, loc: "svcSpot", area: "south", kind: "gas" },
      { id: "tas8", x: 79.37, y: 54.49, loc: "svcSpot", area: "east", kind: "gas" },
      { id: "tas9", x: 38.57, y: 52.03, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "tas10", x: 72.77, y: 73.23, loc: "svcSpot", area: "southEast", kind: "gas" },
      { id: "tas11", x: 64.98, y: 20.09, loc: "svcSpot", area: "north", kind: "gas" },
      { id: "tas12", x: 38.89, y: 45.67, loc: "svcSpot", area: "center", kind: "garage" },
      { id: "tas13", x: 87.5, y: 45.34, loc: "svcSpot", area: "east", kind: "garage" },
      { id: "tas14", x: 90.22, y: 22.57, loc: "svcSpot", area: "northEast", kind: "garage" },
      { id: "tas15", x: 48.35, y: 76.42, loc: "svcSpot", area: "south", kind: "garage" },
      { id: "tas16", x: 54.06, y: 46.35, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "tas17", x: 37.93, y: 67.34, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "tas18", x: 38.79, y: 65.19, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "tas19", x: 88.48, y: 46.23, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas20", x: 87.01, y: 44.03, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas21", x: 79.55, y: 41.06, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas22", x: 38.48, y: 66.61, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "tas23", x: 87.51, y: 47.4, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas24", x: 65.76, y: 52.16, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "tas25", x: 81.53, y: 35.66, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas26", x: 85.04, y: 41.64, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas27", x: 61.96, y: 51.28, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "tas28", x: 39.58, y: 67.33, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "tas29", x: 26.47, y: 56.94, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "tas30", x: 42.57, y: 35.01, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "tas31", x: 76.72, y: 70.49, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "tas32", x: 85.17, y: 48.55, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas33", x: 88.5, y: 51.72, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas34", x: 78.76, y: 71.36, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "tas35", x: 82.39, y: 36.17, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas36", x: 83.37, y: 39.29, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas37", x: 89.06, y: 18.59, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas38", x: 74.05, y: 71.0, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "tas39", x: 83.57, y: 49.37, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas40", x: 84.75, y: 38.43, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas41", x: 22.64, y: 35.78, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "tas42", x: 92.29, y: 26.99, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas43", x: 66.76, y: 63.33, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas44", x: 91.07, y: 33.08, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas45", x: 90.28, y: 29.73, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas46", x: 84.7, y: 45.03, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas47", x: 50.23, y: 81.31, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "tas48", x: 93.22, y: 30.6, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas49", x: 90.69, y: 21.65, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas50", x: 23.91, y: 34.16, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "tas51", x: 93.09, y: 29.14, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas52", x: 85.18, y: 47.18, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "tas53", x: 89.25, y: 32.18, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "tas54", x: 70.49, y: 75.46, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "tas55", x: 50.9, y: 44.01, loc: "svcSpot", area: "center", kind: "vehicle" },
    ],
  },
  {
    mapId: "rondo",
    image: "images/maps/services/rondo.jpg",
    pinCloseup: true,
    builtInMarkers: true,
    rooms: 37,
    pins: [
      { id: "ros1", x: 22.63, y: 9.61, loc: "svcSpot", area: "northWest", kind: "gas" },
      { id: "ros2", x: 56.6, y: 43.16, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "ros3", x: 32.3, y: 35.91, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "ros4", x: 11.1, y: 64.62, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "ros5", x: 42.69, y: 45.21, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "ros6", x: 51.88, y: 78.46, loc: "svcSpot", area: "south", kind: "gas" },
      { id: "ros7", x: 8.05, y: 47.73, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "ros8", x: 66.4, y: 11.01, loc: "svcSpot", area: "northEast", kind: "gas" },
      { id: "ros9", x: 19.79, y: 42.9, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "ros10", x: 36.3, y: 15.92, loc: "svcSpot", area: "north", kind: "gas" },
      { id: "ros11", x: 25.95, y: 79.31, loc: "svcSpot", area: "southWest", kind: "gas" },
      { id: "ros12", x: 58.25, y: 64.47, loc: "svcSpot", area: "center", kind: "gas" },
      { id: "ros13", x: 28.15, y: 57.27, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "ros14", x: 47.4, y: 11.57, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "ros15", x: 12.64, y: 61.66, loc: "svcSpot", area: "west", kind: "garage" },
      { id: "ros16", x: 35.98, y: 30.77, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "ros17", x: 59.09, y: 62.75, loc: "svcSpot", area: "center", kind: "garage" },
      { id: "ros18", x: 73.76, y: 17.58, loc: "svcSpot", area: "northEast", kind: "garage" },
      { id: "ros19", x: 65.32, y: 11.65, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "ros20", x: 29.87, y: 13.07, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "ros21", x: 33.56, y: 65.61, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ros22", x: 18.22, y: 40.55, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ros23", x: 44.99, y: 78.71, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "ros24", x: 61.81, y: 62.35, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ros25", x: 40.8, y: 55.05, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ros26", x: 45.76, y: 26.17, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "ros27", x: 60.62, y: 80.53, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "ros28", x: 15.81, y: 21.44, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "ros29", x: 58.39, y: 44.86, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ros30", x: 26.12, y: 61.48, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ros31", x: 23.04, y: 41.32, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "ros32", x: 36.49, y: 52.43, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ros33", x: 12.88, y: 21.44, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "ros34", x: 56.63, y: 42.32, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "ros35", x: 6.61, y: 25.62, loc: "svcSpot", area: "northWest", kind: "glider" },
      { id: "ros36", x: 10.82, y: 75.28, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "ros37", x: 18.66, y: 16.29, loc: "svcSpot", area: "northWest", kind: "glider" },
    ],
  },
  {
    mapId: "vikendi",
    image: "images/maps/services/vikendi.jpg",
    pinCloseup: true,
    builtInMarkers: true,
    rooms: 66,
    pins: [
      { id: "vis1", x: 24.04, y: 37.63, loc: "svcSpot", area: "west", kind: "gas" },
      { id: "vis2", x: 63.01, y: 70.02, loc: "svcSpot", area: "south", kind: "gas" },
      { id: "vis3", x: 21.68, y: 47.7, loc: "svcSpot", area: "west", kind: "garage" },
      { id: "vis4", x: 60.25, y: 84.32, loc: "svcSpot", area: "south", kind: "garage" },
      { id: "vis5", x: 66.02, y: 36.23, loc: "svcSpot", area: "east", kind: "garage" },
      { id: "vis6", x: 44.38, y: 26.4, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "vis7", x: 16.67, y: 70.01, loc: "svcSpot", area: "southWest", kind: "garage" },
      { id: "vis8", x: 66.75, y: 35.42, loc: "svcSpot", area: "east", kind: "garage" },
      { id: "vis9", x: 63.94, y: 21.62, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "vis10", x: 20.42, y: 47.75, loc: "svcSpot", area: "west", kind: "garage" },
      { id: "vis11", x: 63.73, y: 20.85, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "vis12", x: 19.18, y: 15.74, loc: "svcSpot", area: "northWest", kind: "garage" },
      { id: "vis13", x: 19.12, y: 17.47, loc: "svcSpot", area: "northWest", kind: "garage" },
      { id: "vis14", x: 62.89, y: 21.53, loc: "svcSpot", area: "north", kind: "garage" },
      { id: "vis15", x: 46.47, y: 64.62, loc: "svcSpot", area: "center", kind: "garage" },
      { id: "vis16", x: 41.44, y: 33.32, loc: "svcSpot", area: "center", kind: "garage" },
      { id: "vis17", x: 57.69, y: 41.29, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "vis18", x: 70.09, y: 33.44, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "vis19", x: 64.81, y: 14.73, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "vis20", x: 35.3, y: 14.28, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "vis21", x: 73.83, y: 19.79, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "vis22", x: 64.48, y: 70.01, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis23", x: 47.5, y: 78.92, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis24", x: 48.3, y: 73.68, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis25", x: 45.99, y: 72.84, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis26", x: 47.08, y: 72.52, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis27", x: 46.74, y: 74.57, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis28", x: 45.2, y: 79.68, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis29", x: 45.52, y: 77.99, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis30", x: 55.72, y: 37.88, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "vis31", x: 21.01, y: 52.71, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "vis32", x: 42.68, y: 58.66, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "vis33", x: 53.77, y: 10.67, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "vis34", x: 43.51, y: 58.79, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "vis35", x: 14.9, y: 20.21, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "vis36", x: 64.7, y: 21.05, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "vis37", x: 54.62, y: 65.92, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "vis38", x: 65.55, y: 21.38, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "vis39", x: 13.41, y: 42.97, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "vis40", x: 46.33, y: 50.69, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "vis41", x: 39.73, y: 80.58, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "vis42", x: 47.85, y: 79.98, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "vis43", x: 65.81, y: 15.84, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "vis44", x: 48.93, y: 79.64, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "vis45", x: 57.17, y: 60.38, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "vis46", x: 16.41, y: 46.81, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "vis47", x: 34.42, y: 19.71, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "vis48", x: 48.15, y: 81.0, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "vis49", x: 57.45, y: 61.45, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "vis50", x: 28.88, y: 69.92, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "vis51", x: 34.11, y: 18.64, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "vis52", x: 33.33, y: 19.99, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "vis53", x: 49.75, y: 39.07, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "vis54", x: 33.05, y: 18.97, loc: "svcSpot", area: "north", kind: "glider" },
      { id: "vis55", x: 49.25, y: 80.69, loc: "svcSpot", area: "south", kind: "glider" },
      { id: "vis56", x: 16.72, y: 47.86, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "vis57", x: 28.58, y: 68.87, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "vis58", x: 29.93, y: 69.65, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "vis59", x: 66.88, y: 15.56, loc: "svcSpot", area: "northEast", kind: "glider" },
      { id: "vis60", x: 50.03, y: 40.16, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "vis61", x: 50.8, y: 38.8, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "vis62", x: 66.1, y: 16.93, loc: "svcSpot", area: "northEast", kind: "glider" },
      { id: "vis63", x: 17.52, y: 46.52, loc: "svcSpot", area: "west", kind: "glider" },
      { id: "vis64", x: 29.66, y: 68.56, loc: "svcSpot", area: "southWest", kind: "glider" },
      { id: "vis65", x: 51.08, y: 39.86, loc: "svcSpot", area: "center", kind: "glider" },
      { id: "vis66", x: 67.13, y: 16.64, loc: "svcSpot", area: "northEast", kind: "glider" },
    ],
  },
  {
    mapId: "deston",
    image: "images/maps/services/deston.jpg",
    pinCloseup: true,
    builtInMarkers: true,
    rooms: 49,
    pins: [
      { id: "des1", x: 73.39, y: 59.4, loc: "svcSpot", area: "east", kind: "gas" },
      { id: "des2", x: 65.83, y: 79.41, loc: "svcSpot", area: "south", kind: "gas" },
      { id: "des3", x: 47.45, y: 67.85, loc: "svcSpot", area: "south", kind: "gas" },
      { id: "des4", x: 73.43, y: 60.75, loc: "svcSpot", area: "east", kind: "gas" },
      { id: "des5", x: 58.09, y: 73.9, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "des6", x: 68.03, y: 23.66, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "des7", x: 30.99, y: 28.49, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des8", x: 69.46, y: 35.11, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "des9", x: 26.87, y: 57.07, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des10", x: 44.45, y: 37.94, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "des11", x: 18.25, y: 17.83, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des12", x: 24.19, y: 75.73, loc: "svcSpot", area: "southWest", kind: "vehicle" },
      { id: "des13", x: 62.21, y: 14.71, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "des14", x: 63.26, y: 10.5, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "des15", x: 43.89, y: 23.54, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "des16", x: 20.54, y: 49.87, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des17", x: 30.9, y: 64.38, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des18", x: 32.64, y: 35.34, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des19", x: 9.74, y: 17.4, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des20", x: 5.41, y: 53.25, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des21", x: 45.64, y: 58.91, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "des22", x: 27.24, y: 38.66, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des23", x: 44.74, y: 31.36, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "des24", x: 58.92, y: 76.86, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "des25", x: 32.25, y: 37.33, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des26", x: 4.4, y: 53.55, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des27", x: 31.85, y: 36.55, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des28", x: 34.13, y: 36.52, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "des29", x: 51.85, y: 57.85, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "des30", x: 67.03, y: 42.28, loc: "svcSpot", area: "east", kind: "vehicle" },
      { id: "des31", x: 8.35, y: 19.55, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des32", x: 43.93, y: 67.26, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "des33", x: 9.01, y: 20.23, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des34", x: 19.19, y: 35.06, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des35", x: 57.49, y: 32.57, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "des36", x: 68.25, y: 24.65, loc: "svcSpot", area: "northEast", kind: "vehicle" },
      { id: "des37", x: 67.55, y: 76.88, loc: "svcSpot", area: "southEast", kind: "vehicle" },
      { id: "des38", x: 27.75, y: 56.26, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des39", x: 57.74, y: 72.98, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "des40", x: 41.39, y: 78.75, loc: "svcSpot", area: "south", kind: "vehicle" },
      { id: "des41", x: 24.59, y: 62.97, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des42", x: 9.05, y: 18.46, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des43", x: 23.58, y: 17.65, loc: "svcSpot", area: "northWest", kind: "vehicle" },
      { id: "des44", x: 22.46, y: 39.58, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des45", x: 33.04, y: 36.45, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "des46", x: 4.87, y: 52.29, loc: "svcSpot", area: "west", kind: "vehicle" },
      { id: "des47", x: 46.38, y: 57.97, loc: "svcSpot", area: "center", kind: "vehicle" },
      { id: "des48", x: 35.45, y: 15.53, loc: "svcSpot", area: "north", kind: "vehicle" },
      { id: "des49", x: 21.05, y: 56.34, loc: "svcSpot", area: "west", kind: "vehicle" },
    ],
  }
];













