/** PUBG Steam vehicle guide — seats, fuel, speed (local assets only). */
window.VEHICLE_GUIDE = [
  {
    id: "dacia",
    image: "images/vehicles/dacia.jpg",
    type: "car",
    seats: 4,
    speed: 149,
    health: 1530,
    fuel: 84,
    burn: 7.8,
    maps: ["erangel", "vikendi", "taego", "deston", "rondo"],
    tip: "daciaTip",
  },
  {
    id: "uaz",
    image: "images/vehicles/uaz.jpg",
    type: "car",
    seats: 4,
    speed: 130,
    health: 1680,
    fuel: 95,
    burn: 8.3,
    maps: ["erangel", "miramar", "vikendi", "taego", "deston"],
    tip: "uazTip",
  },
  {
    id: "buggy",
    image: "images/vehicles/buggy.jpg",
    type: "car",
    seats: 2,
    speed: 100,
    health: 1260,
    fuel: 95,
    burn: 6.5,
    maps: ["erangel", "miramar", "taego", "vikendi", "rondo", "deston"],
    tip: "buggyTip",
  },
  {
    id: "pickup",
    image: "images/vehicles/pickup.jpg",
    type: "car",
    seats: 4,
    speed: 110,
    health: 1820,
    fuel: 100,
    burn: 8.0,
    maps: ["miramar", "taego", "deston"],
    tip: "pickupTip",
  },
  {
    id: "mirado",
    image: "images/vehicles/mirado.jpg",
    type: "car",
    seats: 2,
    speed: 152,
    health: 1820,
    fuel: 90,
    burn: 9.5,
    maps: ["miramar"],
    tip: "miradoTip",
  },
  {
    id: "coupeRb",
    image: "images/vehicles/coupe-rb.jpg",
    type: "car",
    seats: 2,
    speed: 150,
    health: 1400,
    fuel: 80,
    burn: 8.5,
    maps: ["erangel", "miramar", "taego", "rondo", "deston"],
    tip: "coupeTip",
  },
  {
    id: "rony",
    image: "images/vehicles/rony.jpg",
    type: "car",
    seats: 4,
    speed: 95,
    health: 1500,
    fuel: 90,
    burn: 7.5,
    maps: ["rondo", "taego"],
    tip: "ronyTip",
  },
  {
    id: "van",
    image: "images/vehicles/van.jpg",
    type: "car",
    seats: 6,
    speed: 110,
    health: 1820,
    fuel: 100,
    burn: 8.2,
    maps: ["erangel", "miramar", "taego", "deston"],
    tip: "vanTip",
  },
  {
    id: "motorcycle",
    image: "images/vehicles/motorcycle.jpg",
    type: "bike",
    seats: 2,
    speed: 152,
    health: 1020,
    fuel: 50,
    burn: 4.2,
    boost: true,
    maps: ["erangel", "miramar", "taego", "vikendi", "rondo", "deston"],
    tip: "motoTip",
  },
  {
    id: "sidecar",
    image: "images/vehicles/sidecar.jpg",
    type: "bike",
    seats: 3,
    speed: 130,
    health: 1100,
    fuel: 55,
    burn: 5.0,
    maps: ["erangel", "miramar", "taego"],
    tip: "sidecarTip",
  },
  {
    id: "dirtBike",
    image: "images/vehicles/dirt-bike.jpg",
    type: "bike",
    seats: 2,
    speed: 130,
    health: 1000,
    fuel: 45,
    burn: 4.0,
    maps: ["miramar", "taego", "rondo"],
    tip: "dirtTip",
  },
  {
    id: "scooter",
    image: "images/vehicles/scooter.jpg",
    type: "bike",
    seats: 2,
    speed: 90,
    health: 800,
    fuel: 35,
    burn: 3.2,
    maps: ["taego", "rondo"],
    tip: "scooterTip",
  },
  {
    id: "snowmobile",
    image: "images/vehicles/snowmobile.jpg",
    type: "snow",
    seats: 2,
    speed: 115,
    health: 1200,
    fuel: 70,
    burn: 6.0,
    maps: ["vikendi"],
    tip: "snowTip",
  },
  {
    id: "boat",
    image: "images/vehicles/boat.jpg",
    type: "water",
    seats: 5,
    speed: 90,
    health: 1500,
    fuel: 200,
    burn: 12.0,
    maps: ["erangel", "miramar", "taego", "vikendi", "deston"],
    tip: "boatTip",
  },
  {
    id: "aquarail",
    image: "images/vehicles/aquarail.jpg",
    type: "water",
    seats: 2,
    speed: 90,
    health: 900,
    fuel: 60,
    burn: 7.0,
    maps: ["erangel", "miramar", "taego", "deston"],
    tip: "aquarailTip",
  },
  {
    id: "glider",
    image: "images/vehicles/glider.jpg",
    type: "air",
    seats: 2,
    speed: 130,
    health: 800,
    fuel: 100,
    burn: 10.0,
    maps: ["erangel", "miramar", "taego", "vikendi", "rondo"],
    tip: "gliderTip",
  },
];

/** Gas can — local image only, no runtime fetch */
window.VEHICLE_FUEL_NOTES = {
  gasCanId: "Gas Can",
  gasCanWeight: 20,
  gasCanImage: "images/other/gas-can.png",
  gasCanFillApprox: 20,
  tip: "gasCanTip",
};

window.VEHICLE_TYPE_ORDER = ["car", "bike", "snow", "water", "air"];
